ALTER TABLE TB_USER ALTER COLUMN user_pw SET DATA TYPE VARCHAR(255);

create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

/*회원가입 테이블 create문*/
CREATE TABLE TB_User
(
    user_no    bigint generated by default as identity,
    user_id    varchar(30),
    user_pw    varchar(30),
    user_name  varchar(30),
    user_email varchar(30),
    user_sex   varchar(10),
    user_age   Int,
    primary key (user_no)
);
insert into tb_user(user_id, user_pw, user_name, user_email, user_sex, user_age)
values ('admin', '1234', 'admin', 'admin@email.com', '남', 24);
ALTER TABLE TB_USER
    ALTER COLUMN user_no RESTART WITH 1;

/* 게시판 테이블 */
CREATE TABLE TB_board
(
    board_no    bigint generated by default as identity,
    board_title varchar(1000),
    board_text  varchar(1000),
    user_no     bigint,
    user_name   varchar(30),
    create_dt   datetime,
    update_dt   datetime,
    PRIMARY KEY (board_no)
);
insert into tb_board(board_title, board_text, user_no, user_name, create_dt                                         )
values ('title', 'text', 11, 'admin', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MM'));
ALTER TABLE TB_BOARD
    ALTER COLUMN BOARD_NO RESTART WITH 1;
SELECT board_no, board_title, board_text, user_no, user_name,
       TO_CHAR(create_dt, 'YYYY-MM-DD HH:MM') cdt, TO_CHAR(update_dt, 'YYYY-MM-DD HH:MM') udt
FROM TB_Board;
/* 댓글 테이블 */
CREATE TABLE TB_comment
(
    comment_no   bigint generated by default as identity,
    comment_text varchar(1000),
    user_no      bigint,
    board_no     bigint,
    user_name    varchar(30),
    create_dt   datetime,
    update_dt   datetime,
    PRIMARY KEY (comment_no)
);
insert into TB_comment(comment_text, user_no, board_no, user_name, create_dt)
values ('comment', 11, 1, 'admin', sysdate);
SELECT comment_no, comment_text, user_no, board_no, user_name,
       TO_CHAR(create_dt, 'YYYY-MM-DD HH:MM') cdt, TO_CHAR(update_dt, 'YYYY-MM-DD HH:MM') udt
FROM TB_COMMENT where board_no = 1;
delete from tb_comment where comment_no = 33;
alter table TB_comment add column create_dt datetime;
ALTER TABLE TB_comment
    ALTER COLUMN comment_no RESTART WITH 1;

-- 테이블 수정문
ALTER TABLE TB_USER RENAME TO "TB_USER";
